#!/bin/sh

USER=mrb
HOST=mrblog.nl
DIR=/srv/http/mrblog.nl/

echo "Regenerating whole site..."
hugo --cleanDestinationDir || exit

echo "Publishing to .$HOST:$DIR'..."
rsync -avz --delete .site/ ${USER}@${HOST}:${DIR} || exit

exit 0
