#!/bin/sh

HOST=mrblog.nl
DIR=/srv/https/mrblog.nl/

echo "Regenerating whole site..."
hugo --cleanDestinationDir || exit

echo "Publishing to .$HOST:$DIR'..."
echo rsync -avz --delete .site/ ${USER}@${HOST}:~/${DIR} || exit

exit 0
