#+layout: post
#+title: Surrendered
#+tags: cobra brakes chassis garage
#+type: post
#+published: true

Unable to set a good time-slot apart for the treatment of the donor
parts, it needs like a 6 hours slot for all the painting and cleaning,
but eager to do something, i started to do some chores on the chassis.

I started with putting all nuts and bolts from the chassis kit loosely
in place. This is to see if i got them all, but also thinking that
their destination is probably the best place to keep them instead of
in a drawer somewhere.

Next up was getting some (more?) wax into the inside of the
chassis. Finding a small enough applicator which would also fit the
venturi attached to the compressor turned out impossible, so one
throwaway aerosol it is then. An easy 15 minute job with nothing to
show for. I needed some more...

Still somewhat hindered by the thought of not doing things in order
for the build I instead created a storage place for the bottom plates
of the car-lift

{%gmg shadowed 403 %}

While a useful end result, I realised I was just making up excuses
and needed a 'real job', so, I decided to do the front-brake-pipe
run. Here's the end result:

{%gmg shadowed 404 %}

Gave me good pair of sore thumbs. I can't attach the p-clips to the
chassis yet, as i want to use the same rivets as GD has been using,
but I do not have such a rivet gun yet. I feel another tool purchase
coming up next week :-)
