#+layout: post
#+title: GD track day
#+tags: cobra chassis
#+type: post
#+published: true

We had a little trip to the UK last weekend. Flew into London
Stansted and hurried to the GD factory. Indeed, my chassis was being
manufactured at the time. It was almost complete, a couple of brackets
were missing and its powder coating. Even without that I was seriously
impressed.

{%gmg shadowed 407 %}

Saturday was mostly spent at the [[http://www.bruntingthorpe.com/][Bruntingthorpe Proving Ground]] where a
little circuit was available for the GD car owners to race their cars
on and for people like myself to take a ride-along. Lots of goodies,
like a very nicely done T70:

{%gmg shadowed 408 %}

The [[http://www.arielatom.com][Arial atom]] exoskeleton cars which the event organiser, [[http://www.bigthunder.co.uk][Big Thunder]]
was using:

{%gmg shadowed 409 %}

And obviously, quite a few GD427's

{%gmg shadowed 410 %}

I had a ride along in both a GD427 (thanks
Hein!) and Andy drove me around the circuit in their T70
demonstrator:

{%gmg shadowed 411 %}

Sunday, we spent a day in Cambridge. Also nice, but erm.. different
;-)
