#+title: Chassis ordered
#+tags: cobra chassis donor-parts engine garage
#+type: post
#+published: true

The chassis has been ordered, that is, Mischa is visiting
[[http://www.gdcars.com][Gardner Douglas]] on wednessday an will order on my behalf. We spoke on
what type of engine I wanted for the car.


 (I managed to decide on the cubic inches, but not on carburated or
injection yet, although i'm beginning to like the LS1 more and more)
Apart from the fact that most decisions on differential, engine,
gearbox etc. are all related and you can't really decide on one at a
time, I'm also seeing the whole car as a /concept/ which should be
/balanced/. If I should choose for a classic 350 cui carburated engine,
for me that has an effect on how the interior should look
too. Likewise, if the choice is for the more modern LS1 or LS6 engine,
that should influence the rest of the looks too. So, the two decisions
were really just:

1. a GM 5.7 liter v8
2. a limited slip differential of ratio 3.54 or 3.31

Those two are enough to get me working on the donor parts and the
rolling chassis. Oh, the outer wall is a bit higher today too...

#+BEGIN_HTML
{% gmg shadowed 429 %}
#+END_HTML
