#+layout: post
#+title: Trial assembly diff plus brakes
#+tags: cobra brakes donor-parts
#+type: post
#+published: true

Having all the parts but one, i did a trial assembly of the
differential, brake discs and handbrake calipers. This is relatively
straightforward, except for the lower bolt of the brake calipers,
which is hard to reach.

The n/s handbrake retraction fork seems a bit too long? Might just be
the trial assembly, i'll figure that out later.

{%gmg shadowed 374 %}

One brake pad location was a bit smaller, making it necessary to shave
a tiny bit of the pad. Scraping of the greenish paint turned out to be
enough.

{%gmg shadowed 375 %}

Having all the parts in place i tried to determine the necessary
shimming to get the brake discs into the midlle of the caliper. It's
not quite clear where you should measure these. There are 4 places on
the inside of the caliper which seem to be machined though, so i took
those.

Being used to metric it means a little bit of converting
back and forth but in the end it looks like i need one shim of '10
thou' and one of '20 thou', o/s and n/s respectively. I'll just order
a bunch and see if on finaly assembly these numbers are still the
same.

{%gmg shadowed 376 %}

The ring top-leftish in the picture is a placeholder for the one
part missing here, a hinge pin for the handbrake. I think it got
somehow lost in the galvanizing sink.

After disassembly i turned the diff on its head and tried to
determine the shimming for the diff bracket. Without the actual shims
available that seemed to be impossible to do. The GD brackets are
drilled to "fit original jaguar shimming" whatever that may be. It
seems to imply there is 'one correct shimming arrangement' here? Would
that then directly set toe-in and toe-out properly? Need to read up on
that I suppose.

So, there's a little puzzle ahead on that. I'm not quite sure what
the proper shimming order should be to a.) get toe-in/out and other
measurements within specs and b.) minimize the number of times i have
to lift up the diff (or any other suspension part for that
matter).

1. shims behind the brake discs so they're in the middle of the caliper;
2. shims behind the diff bracket so the GD brackets fit properly;
3. shims behind the drive axle so the camber is within specs.

Sounds about right?
