#+title: Completing the front hub
#+tags: cobra front-suspension
#+type: post
#+published: true


Back to the front again, completing the wheel hubs. First, put in the
greased up bearing and press in the soaked oil seal:

#+BEGIN_HTML
{%gmg shadowed 326 %}
#+END_HTML


#+BEGIN_HTML
{%gmg shadowed 327 %}
#+END_HTML

Then, put the disc and stub onto the stub axle.

#+BEGIN_HTML
{%gmg shadowed 328 %}
#+END_HTML
#+BEGIN_HTML
{%gmg shadowed 329 %}
#+END_HTML

Grease up the other bearing and press this one in by hand. Put some
more grease on top of the bearing.

#+BEGIN_HTML
{%gmg shadowed 330 %}
#+END_HTML
#+BEGIN_HTML
{%gmg shadowed 331 %}
#+END_HTML

Put the D-washer on top and hand-tighten the nut while turning the
disc.

#+BEGIN_HTML
{%gmg shadowed 332 %}
#+END_HTML
#+BEGIN_HTML
{%gmg shadowed 333 %}
#+END_HTML

While turning the disc, torque up the nut up to 25ftlbs; the disc
should still be able to turn albeit with some resistance. Loosen the
nut by one flat and put on the locking cap and splitpin. I followed
this procedure found at:
[[http://www.bernardembden.com/xjs/hub/index.htm]] after trying to
actually measure the endfloat.

#+BEGIN_HTML
{%gmg shadowed 334 %}
#+END_HTML
#+BEGIN_HTML
{%gmg shadowed 335 %}
#+END_HTML

After that, I filled up the cavity with grease, which takes quite a
bit of it! The new black caps dont come with a hole, so I drilled one
in to be able to let the air out and being able to see when to stop
putting grease in! Once it comes out, you're actually too late
already, because it will keep coming out for 5 minutes more.

#+BEGIN_HTML
{%gmg shadowed 336 %}
#+END_HTML
#+BEGIN_HTML
{%gmg shadowed 337 %}
#+END_HTML
