#+layout: post
#+title: Wheel hubs and uprights part 1
#+tags: cobra front-suspension
#+status: publish
#+type: post
#+published: true

The missing Nord-Lock washers have arrived. This means I can, in
theory, finish the complete buildup of the front-suspension. First off
was fixing the brake discs to the wheel hubs. As mentioned, instead of
the normal spring washers I'm using the Nord-Lock washers where
applicable. This is such a place.

{%gmg shadowed 338 %}

When assembling with these washers it's somewhat important to watch
the surface friction and make sure the pair of rings stay in their
"compressed" state. I do this by sort of overlubricating the contact
surface to make sure the surface friction is less than the friction
between the rings. After that's it's just a matter of torque-ing all
ten of them up and taking a picture.

{%gmg shadowed 339 %}

Next step would be to bring the uprights and the hubs together, at
which point I realised there were 2 oil seals involved needing a 12
hour soak before assembling. So, that more or less stopped the
assembly on this part for today.

{%gmg shadowed 340 %}

And I had them all layed out so neatly.....

{%gmg shadowed 341 %}
