#+layout: post
#+title: Waiting on an engine
#+tags: cobra engine tools
#+type: post
#+published: true


With the engine on the way, I went to [[http://buitelaar.nl][Buitelaar machinehandel]] to pick up an
engine stand and crane and some other things which had been on my
shopping list for a while. Combined it was worth a trip. If you're a
"/tool nerd/" that shop is definitely worth a visit. Don't
forget the drool bib.

#+BEGIN_HTML
{%gmg shadowed 322 %}
#+END_HTML

I went for the el cheapo option on the stand and crane; this showed
during assembly. I had to augment the bolt pack inside with quite a
few to get the things assembled, but alas it's there now.

While I was there I noticed a little gadget which seemed perfect to
set the camber and castor for the suspension.

#+BEGIN_HTML
{%gmg shadowed 323 %}
#+END_HTML

It's capable of doing both absolute and relative angle measurements
and has a magnetic base. Sounds perfect in theory. I'll report back on
how the thing works out in practice.
