#+layout: post
#+title: Handbrake caliper reconditioning
#+tags: cobra brakes donor-parts
#+type: post
#+published: true

Got my parts back from galvanising today. What a difference a
little shine makes! Most of the items were from the donor handbrake
calipers, which were in pretty bad shape when i got them.


#+BEGIN_HTML
{%gmg shadowed 389 %}
#+END_HTML

Using the rivnut tool i bought a while ago, the little covers were
repaired with a new rivnut and although i still am missing a bolt and
some locking thingies, assembling the caliper was pretty
rewarding.

#+BEGIN_HTML
{%gmg shadowed 390 %}
#+END_HTML

I'm not sure about the inside, the clip i have seems different than
what i can find in my manuals. Also the spring on the right seems to
be in the middle of the path were the missing bolt should go to hold
the covers.

#+BEGIN_HTML
{%gmg shadowed 391 %}
#+END_HTML

The other caliper should not be a problem.

The galvanising was sort of an experiment; i found a company nearby
which asks a flat rate for any 'box full of metal parts'. They
galvanise with blue and yellow finish (/blue-ish/ and
/yellow-ish/ i guess). I asked what the limit was for the
parts, but they didn't give me one, so perhaps i should bring the
whole set of suspension parts too?
