#+title: Spraying rear axle parts
#+tags: cobra donor-parts

After the trial run, which went well, I painted the components of
the rear axle today. Planning to do the front axle tomorrow. The self
fabricated rack of some wood and old heating pipe worked well.


#+BEGIN_HTML
{%gmg shadowed 363 %}
#+END_HTML

I'm still wondering about that por15 stuff. I've never seen
anything like it. It's hard to capture the finish in pictures, but
perhaps these two give an idea.

#+BEGIN_HTML
{%gmg shadowed 364 %}
#+END_HTML

#+BEGIN_HTML
{%gmg shadowed 365 %}
#+END_HTML

Especially in the second picture, the finish almost looks
'metal-ish' The spots are the original welding spots. Quite happy with
how it turned out.

I also pressed the bearing cups into the front hubs, that is, only
the large ones. The smaller bearing actually turned out to be too big!
What gives? This bearing comes out of the wheel bearing kit LM258,
which contains a Timken LM12711. The old bearing had a LM12710 cup,
which has an outer diameter which is about 0.7mm smaller. The inner
size of the two is the same, so the roller from the LM258 kit can be
used.

#+BEGIN_HTML
{%gmg shadowed 366 %}
#+END_HTML

Looking at several sources on the internet, I'm not sure what to
make of this. I am not 100% sure of the precise year/model of donor I
have, but I can not match the smaller cup with a Jag model / year
combo, whereas the larger cup is mentioned for several.

Shrug, best get the smaller cup next week and be done with it I
guess.
