#+layout: post
#+title: Rear hub buildup start and grease
#+tags: cobra donor-parts tools
#+type: post
#+published: true

While waiting on the return of all the suspension components from
the galvanizer, there is not much to do. One thing is to prepare the
rear hubs for buildup.

I started to put in the bearing tracks. The fulcrum ones are
relatively easy.

#+BEGIN_HTML
{%gmg shadowed 371 %}
#+END_HTML

The innner and outer bearing track is a different story though. Even
with the proper bearing drifts it takes quite a bit of hammering to
drive them home. After having done two, or rather one and a half i
phoned the local garage with the question if i could use their
press. That made it a lot easier! It did hurt a bit too see my hubs
getting dirty again though.

#+BEGIN_HTML
{%gmg shadowed 372 %}
#+END_HTML

Also did a bit of reading to choose a grease. I ended up with [[http://www.kroon-oil.com/en/products/catalogue/seg_aut/krgr/402/automotive/kroon-oil-greases/high-grade-grease-ht-q9][Kroon
Oil Q9]] It had the words 'high grade' and 'automotive' on it, came with
a free grease gun, which looks a whole lot easier than my current
one....

#+BEGIN_HTML
{%gmg shadowed 373 %}
#+END_HTML

and the stuff is blue! I'm sold.

#+BEGIN_HTML
{%gmg shadowed 374 %}
#+END_HTML
