#+layout: post
#+title: Chores & Holes
#+tags: cobra brakes chassis rear-suspension
#+type: post
#+published: true

Continuing with little jobs to finish the rear end backend. First up
was the final assembly of the top bolts on the diff.  It's not exactly
clear to what value these should be torqued, but I guess the value of
the original Jaguar bolts will come close. The lock-wire went
considerably smoother than earlier (on the diff bracket). I only
needed 3 attempts this time!


#+BEGIN_HTML
{% gmg shadowed 265 %}
#+END_HTML

On to the front, there are six bolts on the suspension which need
their head drilled for the lock-wire. Mostly a patience job, making
sure the bit gets cooled properly and preventing to much pressure on
it. 5 bolts went fine, during the sixth the drill-bit broke. As such
that isn't a disaster, you count on the smaller bits to break soon,
but the bit got stuck in the bolt! The bolts are jaguar specific and
as such a rip-off (around the &euro; 10,- mark I believe). Having no
choice, I ordered a new one.

Having the bench drill now is essential, a hole like below just would
not be possible by hand. (1.5mm hole, 2.5mm finish)

#+BEGIN_HTML
{% gmg shadowed 268 %}
#+END_HTML

Back to the back again. The handbrake mechanism comes with two extra
helper springs which somehow need to be attached to the chassis. There
are two or three locations which would be suitable, but only one of
them was reachable with the rivet tool I have. It remains scary to
drill holes in the chassis.

#+BEGIN_HTML
{%gmg shadowed 266 %}
#+END_HTML

At the right bottom you can see the black dot of a more preferable
location (it pulls on the spring straight instead of in a slight
angle), but unreachable for my tool.

#+BEGIN_HTML
{% gmg shadowed 267 %}
#+END_HTML
