#+layout: post
#+title: Prefitting exhaust
#+tags: cobra exhaust
#+status: publish
#+type: post
#+published: true

Going from the engine to the back of the car I wanted to trial fit as
best as possible the complete exhaust to see where it will attach to
the chassis, how much clearance it gives etc.

Starting at the headers, which are quite nicely made, I noticed that
on the right side the frontmost sparkplug lead and the second
frontmost on the left, are a bit to close to the header for my
taste. It's nearly touching the header on the left side and completely
touching it on the right side.

{% gmg shadowed 269 %}

The other three are positioned much better in between the
headers. Perhaps the alu heat shields can be made a bit shorter?

At the back of the chassis the exhaust is fitted with what looks like
a piece of old tire. I drilled three holes in the rubber, bolted it
onto the bracket and cut a bit of the rubber to make it look neater.

{% gmg shadowed 270 %}

The U-brackets go through and together they hold the middle piece of the exhaust pipes.

{% gmg shadowed 271 %}

Here's an overview picture of the complete underslung exhaust
line. It's quite different from the more traditional (in GD terms)
exhaust where the pipes are together in the center.

{% gmg shadowed 272 %}

I had hoped the ends were a bit closer together, but there's not much
more room to bring them closer, given the current size dampers.
