#+layout: post
#+title: Rear end leftovers
#+tags: cobra rear-suspension
#+status: publish
#+type: post
#+published: true

Looking at the last jobs for the rear end I tried replacing the
straight grease nipples with 45&deg; variants, but getting them
properly positioned to the inside turned out to be quite a
challenge. I'll leave it on the backburner for now.

I double checked the torque on the drive shaft nu and got a helpful
email from [[http://www.cobraclub.com/forum/members/mac-stowt.html][Terry]] about it too. Torqued it to 136Nm and put in the
cotter pin.

#+BEGIN_HTML
{% gmg shadowed 287 %}
#+END_HTML

The overview Terry sent me had torque numbers for the diff cover nuts
as well, so out came the nord-lock washers again and the torque
wrench. Probably not that important, but alas, looks nice at least.

#+BEGIN_HTML
{% gmg shadowed 288 %}
#+END_HTML

Last job was deciding wether to fit the flimsy covers for the drive
shafts. General consensus on the fora was a big no-no, so that made
the decision a bit easier.

So, rear end done! All that's left now is to fit it to the
chassis. (Likely I'll come up with new jobs for it soon, but my list
is empty for now)
