#+layout: post
#+title: Engine bits nearly complete
#+tags:  cobra engine
#+type: post
#+published: true

To complete the engine&mdash;gearbox mating I just need one part now,
which is the pilot bearing for the front of the gearbox. I ordered the
original GM-part earlier, not realising my Tremec gearbox is of the
Ford variety, which has slightly different dimensions. So, I still can
not complete the mating, but there's lots of other (little) stuff I
can complete, such as installing the fuel rail adapter.Click! Done.

{%gmg shadowed 262 %}

In the batch of parts I collected last week, I got the correct length
drive-belt. Installing this is also a job of two seconds. The coverage
on the pulley isn't that big, but the belt only has to drive the
alternator, so it shouldbe ok.


{% gmg shadowed 263 %}

Startmotor can be bolted on now I have the correct length of the
bolts. It's pretty close to the exhaust, I could not even get it
assembled without removing the header, so the starter will probably
need some heat shielding.&nbsp;

{% gmg shadowed 264 %}
