<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta charset="utf-8"/>
<title>{{ page.title }}</title>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>

<!-- Bootstrap -->
<link rel="stylesheet" type="text/css" href="{{site.url}}/assets/css/bootstrap.min.css" />

<!-- syntax highlighting CSS -->
<link rel="stylesheet" type="text/css" href="{{site.url}}/assets/css/syntax.css"/>

<!-- Custom CSS -->
<link rel="stylesheet" type="text/css" href="{{site.url}}/assets/fonts/stylesheet.css"/>
<link rel="stylesheet" type="text/css" href="{{site.url}}/assets/css/main.css"/>

<!-- Feeds we expose -->
<link rel="alternate" type="application/atom+xml" title="Atom 0.3" href="{{site.url}}/feed/atom.xml" />
