<!-- Tag list -->
<span class="glyphicon glyphicon-tags the_tags">
  <a  href="/tag/TODO" rel="tag">
	<span class="label label-default">Tags: $tags$ TODO</span>
  </a>
</span>

<!-- The double dollar is to prevent evaluation by hakyll -->
<!-- $$for(tags)$$ -->
<!--   <a  href="/tag/$$tag$$" rel="tag"> -->
<!--     <span class="label label-default">$$tag$$</span> -->
<!--   </a> -->
<!-- $$endfor$$ -->
