#+title: Maintaining 'seen' info
#+layout: post
#+tags: integration
#+status: publish
#+type: post
#+published: true

#+BEGIN_HTML
<p>As I'm working on several different computers at different locations, with at least two different operating systems, it's sometimes hard to maintain the status of all the message types you need to follow these days.
</p>
<p>Mail, nntp, rss and websites all boil down to messages for me in some form, so I would like to treat them that way. It's not easy to have all places you work behind a computer synced up. I got one step further tho with the help of
<a href="http://www.methodize.org/nntprss">nntp//rss
</a>
</p>
<p>For mail only, my problem has been solved a while ago. Using the Cyrus mail server, i can access my mail from basically anywhere, maintaining status across locations and computers.
</p>
<p>For newsgroups, the solution is basically the same, using shared folders in Cyrus as newsgroups and the 'seen' status of the newsgroups is maintained as well. At this point, the complexity starts. I read newsgroups from different news-servers and chances are about 100% they are NOT Cyrus shared folders.
</p>
<p>So, to be able to maintain status, I have to install a 'proxy' news server which gathers the newsgroups from the different servers and then let the Cyrus server sync with that proxy news server. I'm not sure how posting to those newsgroups would work in this case, but i guess that is manageable by creating accounts in a clever way.
</p>
<p>Now, for RSS-feeds i used to have a separate reader and couldn't figure out why that was needed. I fed
<a href="http://www.google.nl/search?q=rss+to+nntp">'rss to nntp'
</a> into google and after some searching i found a couple of RSS to NNTP and RSS to IMAP gateways.
</p>
<p>Installing
<a href="http://www.methodize.org/nntprss">nntp//rss
</a> was easy enough. It creates a newsgroup for every channel and behaves like a news-server for them, so you can read RSS feeds through your newsreader.
</p>
<p>At this point i read mail, news and rss feeds all with the same program (in my case mozilla), the 'seen' state is only maintained for mail, but at least the RSS subscriptions are all in one place, instead of on all the computers i work on.
</p>
<p>For posting,
<a href="http://www.methodize.org/nntprss">nntp//rss
</a> allows you to define the defined newsgroups as 'writeable' and link a blog to it using the blogger API or metaWebLog. Although pretty unstable and not quite useable yet, i really like the idea, especially if replying to a 'newsgroup' message would show up as a comment on the linked weblog
</p>
<p>In conclusion, integration is possible for me, because i run my own servers. The amount of work and the expertise needed to do it is, as of now, far too high for this to become mainstream.
</p>
#+END_HTML
