#+title: Lowering the treshold
#+layout: post
#+tags: integration
#+status: publish
#+type: post
#+publised true

#+BEGIN_HTML
<p>As mentioned earlier i like to treat weblogs as much as possible as a messaging activity. Not because i like messaging so much, but it has become the major activity in working the internet for me; communicating through news and mail. I find blogging interesting, but the threshold was always a bit high.
<br />
</p>
<p>Especially blogging on linux seems a tab bit less friendly than the excellent clients available for windows, and those didn't fit my pattern. What I did was basically the following:
<br />
</p>
<ol>
<li>searched the net for email gateways to MT (found 3)
<br />
</li>

<li>literally threw the three files into one perl script ( they all had something i needed)
</li>

<li>reorganized and made it fit to be a baseline for me.
</li>
</ol>So, phase 1 is complete, i can post in html with my email client to my blog (through a special email-address linked to it), selecting multiple categories.(by specifying them in a X-Categories custom mail header). Attachments to the email are automatically placed in the right location.
<br />
<br />
Outstanding issues:
<br />
<ol>
<li>a bit better extracting of the message (i left this posting as it is generated, definitely not what you want for all postings, look at the source of this page!)
</li>

<li>keywords, excerpt and extended entry support
</li>

<li>being able to comment through the same mechanism
</li>

<li>get the stylesheet of the blog as a template in the email composer (well, maybe not)
</li>

<li>Editting of posts
</li>

<li>specifying sites to ping
</li>
</ol>
#+END_HTML
