#+title: There is only room for 26 software vendors
#+layout: post
#+tags: integration


Those marketing guys must be rather clueless, lots of software
vendors pick a couple of letters and prefix all their software titles
with it. I can only gues this is due to lack of inspiration or to
create at least the impression that the software is like a suite of
packages which work together (which it does not in most cases) It's
not only the professional marketing departments who lack inspiration,
Open Source developers, whether professional or not, have a liking for
<em>prefabricated</em> names too. Here's the slate what i could come
up with without much research, lots of letters left, so i you have
some plans grab one, while they are still in stock:

 1. The *a* is liberally replaced with a *@* in both names of classes (eM@il) and names of software packages;
 2. The *e* seems to have grown into a prefix to be used for a class of
    software (eMail, eLearning, eCommerce) roughly describing
    *doing the classical thing, but then with the internet*   (whatever that means in practice);
 3. *gnu* - Applications which like to identify themselves (i guess) with the FSF or the GNU software set or the GPL (gnuTella,;
 4. *g* - GNOME stuff;
 5. *i* - Apple (iTunes, iChat);
 6. *k* - KDE applications (kNode, kWrite);
 7. *moz* - Based on mozilla framework (mozBlog, mozEdit) [Note: also the postfix *zilla* is often used];
 8. *x* - X windows applications (xChat, xEyes);
 9. *xar* - Xaraya modules [ hesitated a bit to put this one in ;-) ]
    And of course there is microsoft which just puts MS in front of
    everything. I'm sure there are more examples, the above is by
    head. So, if you want a letter prefix, get one fast; we only have
    26 letters.
