#+title: Moving over
#+layout: post
#+tags: xaraya

I moved over my Moveable Type powered blog over to a Xaraya
install. Long overdue, given that I am a developer on Xaraya, it is
sort of obligatory to run the blog from that package.

I tried to mimick the old look as much as possible. While Xaraya is
certainly more flexible and some things were much easier to do than in
MT, I also noticed that the finesses of MT will take a while to move
over.

Some things which will take some time to come back the full MT way:

 - Trackback functionaliy; while Xaraya supports this, it will take some manual effort to get it to be a friendly player;
 - Inline RDF Moveable type supports by default for autodiscovery;
 - Some templating work is still left (like directly showing the older
   entries);
 - The support for uploading images directly with blog postings;
 - The extended API support.

The above is one of the reasons i moved over, so i have a real life
itch to implement those things in Xaraya. We'll see
