#+title: Eating my own dogfood
#+tags: revision-control xaraya

We have been considering migrating Xaraya to the creole abstraction
layer in the future. Creole is similar to the [[http://adodb.sourceforge.net][adodb]] library we use
now. Originally the support for Creole was created to be able to
implement a MS-SQL proof of concept quickly. After using the library
for a bit I found it much easier to work with than adodb. Creole's API
is much cleaner and it is PHP5 only, which gives us a head start for
future Xaraya versions.


The [[http://monotone.ca][Monotone]] setup we use allows us to test all this without
disturbing main line development. Organizing these bigger changes into
scenario's allows us to isolate these changes and see where they lead
to. The decision to use or to throw away can thus be postponed to a
time when we're ready to do so.

Since replacing the middleware is potentially a very big step, I
noticed we (the Xaraya group) have some trouble making a decision on
what to do with this. Therefore, the creole scenario has been merged
into this site to show that a real life site (albeit a small one) can
be migrated to creole without any effect. (Note: I've been running
creole on other installs for a while now, so I've known this for a
while)


** Verdict
one change was necessary to wrap the 'GetRowAssoc' method
present in adodb but not in creole. Everything else worked directly
after the merge, so my preliminary conclusion if the decision hangs on
'what impact does this have?' is that the impact is very minimal. On
top of that I think that the issues we might run into are not bad
things as such, but chances to improve Xaraya.
