#+title: 5 years of blogging?
#+tags: current-affairs xaraya

I just migrated the posts from this site from Xaraya to a Wordpress
install, just like I did with [[http://cobra.mrblog.nl][My Cobra Blog]] Apparently I have been
playing for about 5 years with it since my first post. The blog
started out as a subdomain of hsdev.com, using an install of Moveable
Type (I forgot the version).


I don't think I used MT for a long time. At the time I was
maintaining/rewriting all the xmlrpc/blogging modules for Xaraya and
it made sense to use my own blog as a testenvironment for it. This
weekend I installed [[http://wordpress.org][Wordpress]] on our servers. Both the "/normal/"
version and the [[http://mu.wordpress.org][WordPress-µ]] (Multi-User) were installed. (I had
already started with the 2.7 beta, but along the way I sort of
realised that the multi user variety is a better choice for me).

So, all new software again for the measly 10 posts I do a year.

The plan is to have mrblog.nl be a 'top-level' kinda thing,
perhaps multi-domain to allow quick creation of blogs and use
subdomains for specific purposes (like the cobra blog and I want to
experiment with a photo-blog at some point too).

We'll see.
