#+title: 5 years of blogging?
#+layout: post
#+tags: current-affairs xaraya


#+BEGIN_HTML

<p>I just migrated the posts from this site from Xaraya to a Wordpress
install, just like I did with
<a href="http://cobra.mrblog.nl">My Cobra Blog
</a>. Apparently I have been playing for about 5 years with it since my first post. The blog started out as a subdomain of hsdev.com, using an install of Moveable Type (I forgot the version).
</p>


<p>
I don't think I used MT for a long time. At the time I was
maintaining/rewriting all the xmlrpc/blogging modules for Xaraya and
it made sense to use my own blog as a testenvironment for it. This
weekend I installed
<a title="Wordpress " href="http://wordpress.org">Wordpress
</a> on our servers. Both the
<em>"normal"
</em> version and the
<a href="http://mu.wordpress.org">WordPress-µ
</a> (Multi-User) were installed. (I had already started with the 2.7 beta, but along the way I sort of realised that the multi user variety is a better choice for me).
</p>
<p>
So, all new software again for the measly 10 posts I do a year.
</p>
<p>
The plan is to have mrblog.nl be a 'top-level' kinda thing, perhaps multi-domain to allow quick creation of blogs and use subdomains for specific purposes (like the cobra blog and I want to experiment with a photo-blog at some point too).

We'll see.
</p>
#+END_HTML
