#+title: Misc.
#+tags: info

Couple of things which were annoying me fixed today. The reading
list on the blog I have deleted. It made the whole thing slow.

While I was at it, I replaced blogger's commenting system with the
[[http://intensedebate.com][Intense debate pluggable commenting system]]. This allows commenting
without popping up a new window or reloading the whole thing, plus it
allows me to respond to those who take the effort to comment,
something which was kinda not possible from within blogger. Let me
know what you think!


To make this post also about the cobra
build, here's a picture of a [[http://www.nordlock.com/][Nord-Lock]] locking washer:

#+BEGIN_HTML
{%gmg shadowed 362 %}
#+END_HTML

In relevant places, like the brake callipers, I'll use these washers
in addition to the lock wire. I'm not a big fan of loctite. Lock-wire,
as such, looks nice but I'm not convinced it is really up to the job
of locking bolts. I do appreciate the beauty of it and its usefulness
in keeping parts from flying around *if* something breaks (or should
that be: '*when* something breaks'?) Nordlock has a [[http://www.nord-lock.com/products/wedge-locking/][convincing
explanation]] on how the washers work on their website. One of their
customers is [[http://www.donkervoort.nl][Donkervoort]] and I like their cars a lot!

The new bearing cups arrived today too, pressing them in was a quick
job. I got them for free, so good service on the part of [[http://www.jaguar-kolvenbach.com/][Kolvenbach
Jaguar]] there.
