#+title: Xaraya commit history on video
#+tags[]: coding integration revision control xaraya

Played a little with the gource log visualizer today. It is typically
used to visualize committed revisions in a revision control system,
although any system that logs events of some kind could be made to
work with it I suppose.


I happen to have a repository of xaraya going back to 2002 in git, so
I thought I'd give it a shot.

...more time passes than originally planned...

*** Result
8 years of commit history in 10 minutes of video. Produced with gource
from a git repository of Xaraya. The video traces the 2.x main branch
back to its origin, repository wise. The start is the import of the
CVS postnuke repository into Bitkeeper. Since then xaraya has switched
to monotone.

#+BEGIN_SRC sh
    gource --stop-position 1.0 \
           --camera-mode overview \
           --bloom-intensity 0.18 \
           --user-image-dir .git/avatar \
           --highlight-all-users \
           --output-framerate 60 \
           -s 0.5 \
           -720x576 \
    	   -a 0.3 \
           --hide filenames \
           --user-scale 1.4 \
           --date-format %Y-%m-%d \
           --disable-progress \
           --output-ppm-stream - \
    | ffmpeg -y -b 3000K -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -vpre default gource.mp4
#+END_SRC

This produced a video of 11 min. 35 seconds. To bring it back to 10
minutes the framerate was increased until the total time fell just
below 10 minutes.﻿

#+BEGIN_HTML
<div class="embed video YouTube">
<iframe width="459" height="344" src="https://www.youtube.com/embed/fIeDCeh3uL8?feature=oembed" frameborder="0" allowfullscreen="">
</iframe></div>
#+END_HTML

I specifically wanted **the whole** history to be in one video of 10
minutes (the Youtube maximum) which means compromising a bit on the
quality. If there are things I can do within these assumptions to
improve the video, I'd like to hear them.
